-- Initial database schema for the AI Social Media Automation demo.
-- Run this file in the Supabase SQL Editor before loading the mock client data.

create table if not exists public.clients (
    client_id text primary key,
    client_name text not null,
    phone_number text,
    service_type text not null,
    service_specialty text not null,
    location text not null,
    state text not null,
    posting_schedule text not null,
    mock_page_name text
);

create table if not exists public.posts (
    id bigint generated by default as identity primary key,
    client_id text not null references public.clients(client_id) on delete cascade,
    client_name text not null,
    service_type text not null,
    service_specialty text not null,
    location text not null,
    state text not null,
    caption text not null,
    platform text not null default 'Facebook',
    status text not null default 'Draft'
        check (
            status in (
                'Draft',
                'approved',
                'needs_revision',
                'human_review_required'
            )
        ),
    qa_notes text,
    revision_count integer not null default 0 check (revision_count >= 0),
    created_at timestamptz not null default now()
);

create table if not exists public.published_posts (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.posts(id) on delete cascade,
    client_id text not null references public.clients(client_id) on delete cascade,
    client_name text not null,
    mock_page_name text,
    platform text not null default 'Facebook',
    caption text not null,
    publish_status text not null default 'published',
    publish_notes text,
    published_at timestamptz not null default now(),
    constraint published_posts_post_id_unique unique (post_id)
);

create index if not exists posts_client_id_idx
    on public.posts(client_id);

create index if not exists posts_status_created_at_idx
    on public.posts(status, created_at);

create index if not exists published_posts_published_at_idx
    on public.published_posts(published_at);

-- This repository uses the anon key without user authentication and contains
-- mock data only. RLS is disabled so the local demo can read and write through
-- the Supabase REST API. Before using real client data, enable RLS and replace
-- this demo access model with authenticated, least-privilege policies.
alter table public.clients disable row level security;
alter table public.posts disable row level security;
alter table public.published_posts disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.clients to anon, authenticated;
grant select, insert, update, delete on table public.posts to anon, authenticated;
grant select, insert, update, delete on table public.published_posts to anon, authenticated;
grant usage, select on sequence public.posts_id_seq to anon, authenticated;
grant usage, select on sequence public.published_posts_id_seq to anon, authenticated;
